"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# 수정 1. class 추가
class SETTING_INFO:
    # import os
    import sqlite3
    from pathlib import Path
    from datetime import datetime
    BASE_DIR = Path(__file__).resolve(
    ).parent.parent                           # 기본경로
    # BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))    # 기본경로
    DB_DIR = BASE_DIR / 'db.sqlite3'                                            # DB 경로
    currentTime = datetime.now().strftime(
        "%Y-%m-%d, %H:%M:%S")                 # 현재시간
    # DB connect
    conn = sqlite3.connect(DB_DIR, check_same_thread=False)

    def __init__(self):                                                     # 생성자
        print(" >>>> Setting dir info <<<< ", SETTING_INFO.currentTime)
        print("\t [SETTING BASE_DIR]   ::", SETTING_INFO.BASE_DIR)
        print("\t [SETTING DB DIR]     ::", SETTING_INFO.DB_DIR)

print(" >>>> Setting dir END- <<<< \t ", SETTING_INFO())



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wv_+*$(hwnft$0$hzd_7*vlz+0g(m&p++x%+5w_woog&cja+f8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 수정 2. 접근 ip '모두'허용


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'APP',                          # 수정 3. APP 앱 추가
    'THEME',                        # 수정 4. THEME 앱 추가
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'NAME': SETTING_INFO.DB_DIR,    # 수정 5. 수정1의 클래스 추가로 변경된 경로 수정
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

LANGUAGE_CODE = 'ko-kr'     # 수정 6. 한국어 패치

TIME_ZONE = 'Asia/Seoul'    # 수정 7. 타임존 수정

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
# STATIC_ROOT = SETTING_INFO.BASE_DIR / 'static/'
STATICFILES_DIRS = [    # 수정 8. 디렉토리 수정
    SETTING_INFO.BASE_DIR / 'static',
    os.path.join(SETTING_INFO.BASE_DIR,"static")
]